import {
  MEMOIR_TYPES,
  INTERVIEW_FORMAT,
  INTERVIEW_LEVEL,
  INTERVIEW_METHOD,
  INTERVIEW_MOOD,
  INTERVIEW_STATUS,
  INTERVIEW_STEP,
  POSITION,
  QUESTION_TYPE,
  SATISFACTION_NOTE,
} from './code';

export const MEMOIR_TYPE_LABELS = {
  [MEMOIR_TYPES.QUICK]: '퀵 회고',
  [MEMOIR_TYPES.GENERAL]: '일반 회고',
} as const;

export const INTERVIEW_FORMAT_LABELS = {
  [INTERVIEW_FORMAT.ONE_ON_ONE]: '일대일 면접',
  [INTERVIEW_FORMAT.ONE_ON_MANY]: '일대다 면접',
  [INTERVIEW_FORMAT.MANY_ON_MANY]: '다대다 면접',
  [INTERVIEW_FORMAT.MANY_ON_ONE]: '다대일 면접',
} as const;

export const INTERVIEW_MOOD_LABELS = {
  [INTERVIEW_MOOD.PRESSURING]: '압박되는',
  [INTERVIEW_MOOD.COMFORTABLE]: '편안한',
  [INTERVIEW_MOOD.QUIET]: '조용한',
  [INTERVIEW_MOOD.SHARP]: '예리한',
  [INTERVIEW_MOOD.FRIENDLY]: '친근한',
} as const;

export const SATISFACTION_NOTE_LABELS = {
  [SATISFACTION_NOTE.SATISFIES]: '만족',
  [SATISFACTION_NOTE.NEUTRAL]: '보통',
  [SATISFACTION_NOTE.DISSATISFIED]: '불만족',
} as const;

export const INTERVIEW_LEVEL_LABELS = {
  [INTERVIEW_LEVEL.EASY]: '쉬움',
  [INTERVIEW_LEVEL.NORMAL]: '보통',
  [INTERVIEW_LEVEL.HARD]: '어려움',
} as const;

export const INTERVIEW_METHOD_LABELS = {
  [INTERVIEW_METHOD.FACE_TO_FACE]: '대면',
  [INTERVIEW_METHOD.NON_FACE_TO_FACE]: '비대면',
} as const;

export const INTERVIEW_STATUS_LABELS = {
  [INTERVIEW_STATUS.PASS]: '합격',
  [INTERVIEW_STATUS.FAIL]: '불합격',
  [INTERVIEW_STATUS.PENDING]: '대기중',
} as const;

export const INTERVIEW_STEP_LABELS = {
  [INTERVIEW_STEP.FIRST_INTERVIEW]: '1차 면접',
  [INTERVIEW_STEP.SECOND_INTERVIEW]: '2차 면접',
  [INTERVIEW_STEP.FINAL_INTERVIEW]: '최종 면접',
} as const;

export const POSITION_LABELS = {
  [POSITION.PLANNING_STRATEGY]: '기획·전략',
  [POSITION.MARKETING_PR]: '마케팅·홍보',
  [POSITION.ACCOUNTING_FINANCE]: '회계·세무·재무',
  [POSITION.HR]: '인사·노무·HRD',
  [POSITION.ADMIN_LEGAL]: '총무·법무·사무',
  [POSITION.DEVELOPMENT_DATA]: '개발·데이터',
  [POSITION.DESIGN]: '디자인',
  [POSITION.SALES_CUSTOMER]: '영업·고객관리',
  [POSITION.PURCHASE_LOGISTICS]: '구매·자재·물류',
  [POSITION.DRIVING_DELIVERY]: '운전·운송·배송',
  [POSITION.SERVICE]: '서비스',
  [POSITION.CONSTRUCTION_ARCHITECTURE]: '건설·건축',
  [POSITION.FINANCE_INSURANCE]: '금융·보험',
  [POSITION.PUBLIC_WELFARE]: '공공·복지',
} as const;

export const QUESTION_TYPE_LABELS = {
  [QUESTION_TYPE.PERSONALITY]: '인성질문',
  [QUESTION_TYPE.JOB]: '직무질문',
  [QUESTION_TYPE.EXPERIENCE]: '경험질문',
  [QUESTION_TYPE.COMPANY]: '회사질문',
  [QUESTION_TYPE.FOLLOW_UP]: '꼬리질문',
} as const;
