import type { Metadata } from 'next';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import '@/styles/globals.css';

import QueryClientProvider from './QueryClientProvider';
import NextAuthProvider from './NextAuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="mx-auto flex max-w-[600px] flex-col">
        <NextAuthProvider>
          <QueryClientProvider>
            {children}
            <ReactQueryDevtools />
          </QueryClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
